resources:
  - ../default

patchesStrategicMerge:
  - config_patch.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: tpu-provisioner-manager-role
  patch: |-
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - slice.accelerator.gke.io
        resources:
        - slices
        verbs:
        - '*'
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - slice.accelerator.gke.io
        resources:
        - slices/status
        verbs:
        - get